# Generated by Django 3.2.4 on 2022-07-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaffeineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254, verbose_name='User Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('venue_address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120, verbose_name='Contact Phone No.')),
                ('web', models.URLField(verbose_name='Website Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('manager', models.CharField(max_length=120)),
                ('event_desc', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, to='CafClubApp.CaffeineUser')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CafClubApp.venue')),
            ],
        ),
    ]
