# Generated by Django 3.2.4 on 2022-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafClubApp', '0002_venue_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Website Address'),
        ),
    ]
